apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: sample-vr-node-app
  labels:
    app: sample-vr-node-app
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: sample-node-app
    spec:
      containers:
      - name: sample-vr-node-app
        image: aha04612/watson-vr-nodedemo:v1.0
        command:
        ports:
          - containerPort: 3000
