apiVersion: v1
kind: Service
metadata:
  name: sample-vr-node-app
  labels:
    app: sample-vr-node-app
spec:
  ports:
  - port: 3000
    targetPort: 3000
  selector:
    app: sample-vr-node-app
  type: NodePort